### ISSUE TITLE
Checklist for GCP Project migration

### ISSUE THREAD

**Issue by ihsw** [sotah-inc/infra#1]
# GCP Project Migration

This issue will provide a checklist used for going over the assets to migrate from the old GCP project to the new GCP project.

### Serverless VPC Connector

- [x] Create VPC Connector in `us-central` region

### Cloud Run

Ensure Cloud Run service exists for `sotah-inc/api`:
- [ ] `sotah-inc/api` `cloudbuild.yaml` deploys to Cloud Run service
- [ ] service allows unauthenticated requests (public-facing)
- [ ] service uses VPC Connector for access to private IPs
- [ ] service [uses env var](https://cloud.google.com/run/docs/configuring/environment-variables) to access NATS host
- [ ] service [uses env var](https://cloud.google.com/run/docs/configuring/environment-variables) to access Cloud SQL host
- [ ] service has domain mapping to Cloud Run service
- [ ] update Cloud DNS to point `api.sotah.info` to Cloud Run service

### Cloud Load Balancer

Create one load balancer with:
- [x] HTTP, Premium network tier
- [x] HTTPS, Premium network tier (with SSL cert from old environment)
- [x] `item-icons` back-end pointing to `sotah-item-icons` storage bucket, Cloud CDN enabled
- [x] `sotah-backend-service` back-end pointing to unmanaged instance group with `n1-instance-2 instance in it, Cloud CDN disabled
- [x] All unmatched traffic goes to `sotah-backend-service`
- [x] `item-icons.sotah.info` goes to the `item-icons` backend
- [x] Cloud DNS points to new Load Balancer public IP

### Cloud Source Repositories

Add repository mirroring for:
- [x] `sotah-inc/server`
- [x] `sotah-inc/api`
- [x] `sotah-inc/client`

### Cloud Functions

Deploy the following in the new project:
- [x] `CleanupExpiredManifest`
- [x] `DownloadAuctions`
- [x] `SyncItemIcons`
- [x] `SyncItems`

### Cloud Scheduler

For `auctions-collector` job:
- [x] Frequency has `*/20 * * * *` (every 20 minutes)
- [x] Target is `downloadAllAuctions` PubSub topic
- [x] Timezone is US and Eastern Time
- [x] Payload is `{}`

For `auctions-manifest-cleanup` job:
- [x] Frequency has `0 12 * * 0` (Sunday at 12pm)
- [x] Target is `cleanupAllExpiredManifests` PubSub topic
- [x] Timezone is US and Eastern Time
- [x] Payload is `{}`

For `pricelist-histories-cleanup` job:
- [x] Frequency has `0 12 * * 0` (Sunday at 12pm)
- [x] Target is `cleanupAllPricelistHistories` PubSub topic
- [x] Timezone is US and Eastern Time
- [x] Payload is `{}`

### AppEngine

For `sotah-inc/client`:
- [x] Ensure AppEngine service exists
- [x] Ensure custom domain `sotah.info` points to AppEngine service, Google-managed and auto-renewing SSL security

### Compute Engine

Ensure following instances are created:
- [x] `f1-micro` instance for hosting long-lived worker processes unsuitable for Cloud Functions
- [x] 10GB standard persistent disk for boot disk
- [x] `n1-standard-2` instance for hosting various BoltDB databases that require high-IOPS disk access
- [x] 10GB standard persistent disk for boot disk
- [x] 375GB NVMe SSD for local disk

### Cloud Build

Add triggers for:
- [x] `sotah-inc/api`
- [x] `sotah-inc/client`
- [x] `sotah-inc/server`

Check trigger codebases for any project-specific env yaml files:
- [x] `sotah-inc/api`
- [x] `sotah-inc/client`
- [x] `sotah-inc/server`

### Cloud SQL

- [x] Create database dump of `sotah-sql`
- [x] Create new instance in new prod environment
- [x] New instance should be lowest tier but with high-availability (HA)
- [x] Upload database dump to new prod `sotah-sql` instance

### Cloud DNS

- [x] Ensure legacy Cloud DNS zone is deleted

Ensure new zone has the following:
- [x] Named `sotah-prod` with DNS name `sotah.info`
- [x] Get new Load Balancer IP
- [ ] `sotah.info` A record that points to AppEngine IP
- [x] `sotah.info` MX record that points to Google Apps mail servers
- [x] `sotah.info` NS record (exists by default)
- [x] `sotah.info` SOA record (exists by default)
- [x] `*.sotah.info` A record that points to Load Balancer IP

### Google Domains

- [x] Update Google Domains DNS to use new Cloud DNS zone

### Cloud Storage

Ensure destination buckets exist:
- [x] sotah-auctions-manifest
- [x] sotah-item-icons
- [x] sotah-live-auctions
- [x] sotah-pricelist-histories
- [x] sotah-raw-auctions
- [x] sotah_boot
- [x] sotah_items
- [x] sotah_realms

Ensure transfer service account has Storage Admin privileges:
- [x] sotah-auctions-manifest
- [x] sotah-item-icons
- [x] sotah-live-auctions
- [x] sotah-pricelist-histories
- [x] sotah-raw-auctions
- [x] sotah_boot
- [x] sotah_items
- [x] sotah_realms

Copy objects from source buckets to destination buckets:
- [x] ~~auctions-manifest -> sotah-auctions-manifest~~
- [x] item-icons -> sotah-item-icons
- [ ] ~~live-auctions -> sotah-live-auctions~~
- [x] pricelist-histories -> sotah-pricelist-histories
- [ ] ~~raw-auctions -> sotah-raw-auctions~~
- [x] sotah-boot -> sotah_boot
- [x] sotah-items -> sotah_items
- [x] sotah-realms -> sotah_realms

Ensure source buckets are cleared and deleted:
- [x] auctions-manifest
- [x] item-icons
- [x] live-auctions
- [x] pricelist-histories
- [x] raw-auctions
- [x] sotah-boot
- [x] sotah-items
- [x] sotah-realms

**Comment by ihsw** [comment]
Closing and ignoring Cloud Run section as Cloud Run does not currently support routing to private VPC network (via VPC Connector.)
